trigger:
  branches:
    include:
      - feature/*

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: ci-variables

steps:
- checkout: self

- task: Bash@3
  displayName: Check SECRET_KEY
  inputs:
    targetType: inline
    script: |
      if [ -z "$SECRET" ]; then
        echo "SECRET_KEY is NOT SET"
        exit 1
      fi

      echo "SECRET_KEY is SET"
  env:
    SECRET_KEY: $(SECRET_KEY)