trigger:
  branches:
    include:
      - feature/*

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  MY_SECRET: "my-temporary-ci-secret-key"

steps:
- task: Bash@3
  displayName: Test SECRET_KEY Mapping
  env:
    SECRET: $(MY_SECRET)
  inputs:
    targetType: inline
    script: |
      echo "SECRET_KEY=[$SECRET]"
      echo "Length=${#SECRET}"

      if [ -z "$SECRET" ]; then
        echo " SECRET_KEY is NOT SET"
        exit 1
      else
        echo " SECRET_KEY is SET"
      fi