sonar.projectKey=ShibuPS007_Chatbot
sonar.projectName=ShibuPS007_Chatbot
sonar.host.url=http://40.81.232.167:9000
sonar.sources=backend,frontend
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/myenv/**,**/.pytest_cache/**,**/chroma_db/**,**/uploads/**,**/frontend/node_modules/**,**/.env,test.db
sonar.python.coverage.reportPaths=coverage.xml